# Generated by Django 6.0.2 on 2026-02-15 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Currículo para Vaga Python', max_length=100)),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=30)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=300)),
                ('resumo_profissional', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: AWS Cloud Practitioner', max_length=200)),
                ('organizacao_emissora', models.CharField(help_text='Ex: Amazon, Google, Alura', max_length=200)),
                ('data_emissao', models.DateField()),
                ('link_validacao', models.URLField(blank=True, null=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='curriculo.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=300)),
                ('empresa', models.CharField(max_length=300)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(help_text='Descreva suas atividades e conquistas.')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='curriculo.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=300)),
                ('curso', models.CharField(max_length=300)),
                ('nivel_de_escolaridade', models.CharField(choices=[('TEC', 'Tecnólogo'), ('BAC', 'Bacharelado'), ('LIC', 'Licenciatura'), ('MES', 'Mestrado'), ('DOC', 'Doutorado'), ('POS', 'Pós-Graduação/MBA')], max_length=3)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to='curriculo.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tecnico', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('BAS', 'Básico'), ('INT', 'Intermediário'), ('AVA', 'Avançado'), ('PRO', 'Profissional')], max_length=3)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='curriculo.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Inglês, Espanhol, Francês', max_length=100)),
                ('nivel', models.CharField(choices=[('BAS', 'Básico'), ('INT', 'Intermediário'), ('AVA', 'Avançado'), ('FLU', 'Fluente'), ('NAT', 'Nativo')], max_length=3)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='curriculo.curriculo')),
            ],
        ),
    ]
